Nova 4 Upgrade
webparking/nova-belongs-to-dependency pull request #5
Opened 2022-05-07 16:12 UTC by the-alichemist

2022-05-23 07:57 UTC, remkobrenters commented
Mr @RVxLab do you want to look into this PR?

2022-05-23 08:29 UTC, RVxLab commented
I can't make a proper judgement call on this as I don't use Nova 4. The only suggestion I have is to set the PHP requirement to `^7.3|^8` as 7.3 is the minimum now.

2022-05-23 09:13 UTC, remkobrenters commented
That's fast :) thanks. Makes sense. @dgerrese do you think you can look into this as I have no Nova 4 running anywhere yet.

2022-05-23 09:42 UTC, RVxLab requested changes
I looked a little more in depth, nothing looks particularly wrong but someone else needs to do a final call.

Also @the-alichemist if you can please minify the JS that'd be great.

2022-05-23 09:42 UTC, RVxLab commented on composer.json
>          "php": ">=7.1.0",
```suggestion
        "php": "^7.3|^8",
```

2022-05-23 15:39 UTC, dgerrese commented
Tested this in Nova 4 and seems to work.
I don't see any issues other than @RVxLab's suggestions.

2022-05-23 15:41 UTC, remkobrenters commented
@the-alichemist are you willing to change the PR a bit so we can merge it?

2022-05-28 23:12 UTC, the-alichemist commented
@RVxLab @remkobrenters Sorry for the late reply. Suggestions have been implemented.

2022-05-28 23:30 UTC, RVxLab approved these changes

2022-05-28 23:31 UTC, merged

2022-05-28 23:32 UTC, RVxLab commented
Thank you for the PR!